### PR TITLE
Swap opened and closed connection counter names

### LINKED ISSUE #74: Wrong counter names
If I'm not mistaken, these two counter names must be swapped:

https://github.com/prebid/prebid-cache/blob/282ec907e616c3a7d49e903249b8595b7ac12922/metrics/prometheus/prometheus.go#L124
https://github.com/prebid/prebid-cache/blob/282ec907e616c3a7d49e903249b8595b7ac12922/metrics/prometheus/prometheus.go#L125

### PR DESCRIPTION
**Pull request by guscarreon**
Fixes #74. Thanks @ix-prebid-support, pretty good catch.

### CODE REVIEW

File: metrics/prometheus/prometheus.go [hunk 1]
```diff
@@ -121,8 +121,8 @@ func CreatePrometheusMetrics(cfg config.PrometheusMetrics) *PrometheusMetrics {
 			),
 		},
 		Connections: &PrometheusConnectionMetrics{
-			ConnectionsClosed: newSingleCounter(cfg, registry, ConnOpenedKey, "Count the number of closed connections"),
-			ConnectionsOpened: newSingleCounter(cfg, registry, ConnClosedKey, "Count the number of open connections"),
+			ConnectionsClosed: newSingleCounter(cfg, registry, ConnClosedKey, "Count the number of closed connections"),
+			ConnectionsOpened: newSingleCounter(cfg, registry, ConnOpenedKey, "Count the number of open connections"),
```
Comment (SyntaxNode) [inline metrics/prometheus/prometheus.go:125]: Is it possible to add a unit test? ... as to avoid repeating this mistake in the future.

**Review by VeronikaSolovei9 — APPROVED** [review]
LGTM

**Review by bsardo — APPROVED** [review]
LGTM
